# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9a5a5017708a222bc3747f03ca9d62956e1cf037b56dab0e1d235cb7e23ce7c20a96ae56e6670d2ed48217aa9263fda4e27d02d3b47bf313b5c747bc3fb6f0

test:
  secret_key_base: 0aca15fd245eda85e2635525412ee2985ad918600ea5d4739e635ae50cc07f5a587e8536ebaa75d28c5a78e386475413ce89fd6f7810a4884277c013c7f00e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
